[project]
name = "coding-collects"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pytest>=8.3.4",
    "pytest-cache>=1.0",
    "pytest-subtests>=0.14.1",
]
