stack = ["task01", "task02", "task03"]
print("now:", stack)
stack.append("task04")
print("now:", stack)
stack.append("task05")
print("now:", stack)
stack.pop()
print("now:", stack)
stack.pop()
print("now:", stack)